version: '2'
services:
  clojure-node:
    image: broadinstitute/clojure-node
    volumes:
      - work:/w
      - jar-cache:/root/.m2
      - node-modules:/w/node_modules
    working_dir: /w
    command: bash
    stdin_open: true
    tty: true
    environment:
      - npm_config_unsafe_perm="true"
  slimerjs:
    image: evpavel/slimerjs-alpine
    volumes:
      - work:/w
    working_dir: /w
    command: bash
    stdin_open: true
    tty: true
volumes:
  work:
  jar-cache:
    external: true
  node-modules:
    external: true
