version: '2'
services:
  clojure-node:
    image: broadinstitute/clojure-node
    volumes:
      - work:/w
      - jar-cache:/root/.m2
    working_dir: /w
    command: bash
    stdin_open: true
    tty: true
  phantomjs:
    image: wernight/phantomjs:2
    volumes:
      - work:/w
    working_dir: /w
    command: bash
    stdin_open: true
    tty: true
  mkdir:
    image: broadinstitute/clojure-node
    volumes:
      - work:/w
    working_dir: /w
    command: mkdir -p resources/public
  server:
    depends_on:
      - mkdir
    image: broadinstitute/clojure-node
    volumes:
      - work:/w
    working_dir: /w/resources/public
    command: bash -c 'npm install -g node-static && static -a 0.0.0.0 -p 80'
volumes:
  work:
  jar-cache:
    external: true
