name: dsp-appsec-trivy
on:
  schedule:
    - cron:  '0 14 * * 1' # each Monday at 9am EST

jobs:
  appsec-trivy:
    # Parse Dockerfile and build, scan image if a "blessed" base image is not used
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    env:
      SARIF_PATH: trivy-results.sarif

    steps:
      - uses: actions/checkout@v2

      - uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          image: broadinstitute/firecloud-ui:develop
          sarif: ${{ env.SARIF_PATH }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ env.SARIF_PATH }}
